# Generated by Django 4.2.1 on 2024-02-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='women',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
