# Generated by Django 4.2.1 on 2024-04-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_women_photo_new_alter_women_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='women',
            name='photo_new',
            field=models.CharField(default='NoPhoto', max_length=255),
        ),
    ]
