# Generated by Django 4.2.1 on 2024-02-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_alter_women_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='photo',
            field=models.CharField(default='NoPhoto', max_length=255),
        ),
    ]
