# Generated by Django 4.2.1 on 2024-02-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0007_alter_women_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='women',
            name='cat',
        ),
    ]
