# Generated by Django 4.2.1 on 2024-02-24 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0008_remove_women_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='women.category'),
        ),
    ]
